### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#379]
- [x] Fix bounce scroll thing
- [x] Fix username too big for top bar
- [x] Contributor view
- [x] Use autolayout for drawer button and FAB to fix display issues
- [ ] Fix new posts not loading? maybe if I can reproduce it
- [x] Change Pro boolean so they can purchase it for real
- [x] Pro in other currencies still shows old price as $4.99
- [x] Remove alpha testing notification
- [x] Un comment rate bar
- [x] Add FAB toggle to welcome screen
- [x] Remove gallery mode!

**Comment by ccrama** [comment]
We are ready for release! Can't believe two years has led up to this :)
